version: '3.8'
networks:
    admin:
        driver: bridge
services:
    admin:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        ports:
            - "8001:8000"
        depends_on:
            -   admin_db
        networks:
            - admin
    admin_db:
        image: mysql
        environment:
            MYSQL_DATABASE: admin
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - "33060:3306"
        networks:
            - admin
